name: BUILD_AND_DEPLOY

on: [push]

jobs:
  build_and_deploy:

    runs-on: sdenel/blog-builder

    steps:
    - uses: actions/checkout@v1
    - name: run builder doctests
      run: python3 -m doctest builder.py
    - name: Build
      run: COMPILATION_MODE=PROD ./builder.py
    - name: Deploy
      run: |
        pip3 install awscli
        export AWS_ACCESS_KEY_ID="AKIAYWWIADIBMC6TI4GD" # AWS_SECRET_ACCESS_KEY is a Github secret
        export AWS_DEFAULT_REGION="eu-west-1"
        aws s3 sync . s3://sdenel-blog/ --delete
        aws cloudfront create-invalidation --distribution-id E1L0TUDHUWNSDT --paths "/*"
